#!/usr/bin/env node
/**
 * Regenerates the refindery OpenAPI snapshot and the generated TS types.
 *
 * Modes:
 *   node scripts/gen-api.mjs          Refresh src/modules/refindery/domain/
 *                                     openapi.json from a running refindery
 *                                     (VITE_REFINDERY_TARGET, default
 *                                     http://127.0.0.1:8000). Falls back to
 *                                     dumping the spec offline from a sibling
 *                                     backend checkout (REFINDERY_REPO, default
 *                                     ../refindery) via `uv run` and the
 *                                     side-effect-free create_openapi_app().
 *                                     Then regenerates api.gen.ts.
 *   node scripts/gen-api.mjs --check  Regenerate from the COMMITTED snapshot
 *                                     only (no network — CI-safe) and exit 1
 *                                     if api.gen.ts is stale.
 *
 * Output is byte-stable for a given openapi-typescript version (exact-pinned
 * in package.json): the Node API is used directly and the banner carries no
 * timestamp, so `--check` can compare strings.
 */
import { execFile } from 'node:child_process';
import { existsSync } from 'node:fs';
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { promisify } from 'node:util';
import openapiTS, { astToString } from 'openapi-typescript';

const execFileAsync = promisify(execFile);

const SPEC_PATH = 'src/modules/refindery/domain/openapi.json';
const OUTPUT_PATH = 'src/modules/refindery/domain/api.gen.ts';

const HEADER = `/**
 * Generated by \`pnpm gen:api\` from openapi.json — do not edit.
 * Refresh the snapshot against a running refindery with \`pnpm gen:api\`;
 * CI verifies freshness against the committed spec via \`pnpm gen:api:check\`.
 */
`;

const PYTHON_DUMP =
  'import json; from refindery.api.app import create_openapi_app; ' +
  'print(json.dumps(create_openapi_app().openapi()))';

async function generateTypes(specJson) {
  // defaultNonNullable: false — a field with a server-side default is optional
  // on the wire (requests may omit it), not required.
  const ast = await openapiTS(specJson, { defaultNonNullable: false });
  return HEADER + astToString(ast);
}

async function dumpFromSiblingRepo(fetchError) {
  const repo =
    process.env.REFINDERY_REPO ??
    path.resolve(process.cwd(), '..', 'refindery');
  if (!existsSync(repo)) {
    throw new Error(
      `Cannot fetch openapi.json (${fetchError.message}) and no backend checkout at ${repo}. ` +
        'Start a refindery instance or set REFINDERY_REPO.'
    );
  }
  console.log(`Backend unreachable; dumping spec offline from ${repo} …`);
  const { stdout } = await execFileAsync(
    'uv',
    ['run', 'python', '-c', PYTHON_DUMP],
    { cwd: repo, maxBuffer: 64 * 1024 * 1024 }
  );
  return stdout;
}

async function fetchSpec() {
  const target = process.env.VITE_REFINDERY_TARGET ?? 'http://127.0.0.1:8000';
  try {
    const response = await fetch(new URL('/openapi.json', target), {
      signal: AbortSignal.timeout(5000),
    });
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    console.log(`Fetched openapi.json from ${target}.`);
    return await response.text();
  } catch (error) {
    return dumpFromSiblingRepo(
      error instanceof Error ? error : new Error(String(error))
    );
  }
}

async function check() {
  const specText = await readFile(SPEC_PATH, 'utf8');
  const expected = await generateTypes(JSON.parse(specText));
  const actual = await readFile(OUTPUT_PATH, 'utf8').catch(() => '');
  if (expected !== actual) {
    console.error(
      `✖ ${OUTPUT_PATH} is stale relative to ${SPEC_PATH}. Run \`pnpm gen:api\`.`
    );
    process.exit(1);
  }
  console.log(`✓ ${OUTPUT_PATH} matches ${SPEC_PATH}.`);
}

async function regenerate() {
  const spec = JSON.parse(await fetchSpec());
  await writeFile(SPEC_PATH, `${JSON.stringify(spec, null, 2)}\n`);
  await writeFile(OUTPUT_PATH, await generateTypes(spec));
  console.log(`Wrote ${SPEC_PATH} and ${OUTPUT_PATH}.`);
}

if (process.argv.includes('--check')) {
  await check();
} else {
  await regenerate();
}
