/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellSystemRouteImport } from './routes/_shell/system'
import { Route as ShellSettingsRouteImport } from './routes/_shell/settings'
import { Route as ShellSearchRouteImport } from './routes/_shell/search'
import { Route as ShellModelsRouteImport } from './routes/_shell/models'
import { Route as ShellJobsRouteImport } from './routes/_shell/jobs'
import { Route as ShellEntitiesRouteImport } from './routes/_shell/entities'
import { Route as ShellClustersRouteImport } from './routes/_shell/clusters'
import { Route as ShellPagesIndexRouteImport } from './routes/_shell/pages/index'
import { Route as ApiTelemetrySentryTunnelRouteImport } from './routes/api/telemetry.sentry-tunnel'
import { Route as ApiTelemetryLogsRouteImport } from './routes/api/telemetry.logs'
import { Route as ShellPagesPageIdRouteImport } from './routes/_shell/pages/$pageId'
import { Route as ApiTelemetryOtelV1TracesRouteImport } from './routes/api/telemetry.otel.v1.traces'
import { Route as ApiTelemetryOtelV1MetricsRouteImport } from './routes/api/telemetry.otel.v1.metrics'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSystemRoute = ShellSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSearchRoute = ShellSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ShellRoute,
} as any)
const ShellModelsRoute = ShellModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => ShellRoute,
} as any)
const ShellJobsRoute = ShellJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => ShellRoute,
} as any)
const ShellEntitiesRoute = ShellEntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => ShellRoute,
} as any)
const ShellClustersRoute = ShellClustersRouteImport.update({
  id: '/clusters',
  path: '/clusters',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPagesIndexRoute = ShellPagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => ShellRoute,
} as any)
const ApiTelemetrySentryTunnelRoute =
  ApiTelemetrySentryTunnelRouteImport.update({
    id: '/api/telemetry/sentry-tunnel',
    path: '/api/telemetry/sentry-tunnel',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTelemetryLogsRoute = ApiTelemetryLogsRouteImport.update({
  id: '/api/telemetry/logs',
  path: '/api/telemetry/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellPagesPageIdRoute = ShellPagesPageIdRouteImport.update({
  id: '/pages/$pageId',
  path: '/pages/$pageId',
  getParentRoute: () => ShellRoute,
} as any)
const ApiTelemetryOtelV1TracesRoute =
  ApiTelemetryOtelV1TracesRouteImport.update({
    id: '/api/telemetry/otel/v1/traces',
    path: '/api/telemetry/otel/v1/traces',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTelemetryOtelV1MetricsRoute =
  ApiTelemetryOtelV1MetricsRouteImport.update({
    id: '/api/telemetry/otel/v1/metrics',
    path: '/api/telemetry/otel/v1/metrics',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/clusters': typeof ShellClustersRoute
  '/entities': typeof ShellEntitiesRoute
  '/jobs': typeof ShellJobsRoute
  '/models': typeof ShellModelsRoute
  '/search': typeof ShellSearchRoute
  '/settings': typeof ShellSettingsRoute
  '/system': typeof ShellSystemRoute
  '/pages/$pageId': typeof ShellPagesPageIdRoute
  '/api/telemetry/logs': typeof ApiTelemetryLogsRoute
  '/api/telemetry/sentry-tunnel': typeof ApiTelemetrySentryTunnelRoute
  '/pages/': typeof ShellPagesIndexRoute
  '/api/telemetry/otel/v1/metrics': typeof ApiTelemetryOtelV1MetricsRoute
  '/api/telemetry/otel/v1/traces': typeof ApiTelemetryOtelV1TracesRoute
}
export interface FileRoutesByTo {
  '/clusters': typeof ShellClustersRoute
  '/entities': typeof ShellEntitiesRoute
  '/jobs': typeof ShellJobsRoute
  '/models': typeof ShellModelsRoute
  '/search': typeof ShellSearchRoute
  '/settings': typeof ShellSettingsRoute
  '/system': typeof ShellSystemRoute
  '/': typeof ShellIndexRoute
  '/pages/$pageId': typeof ShellPagesPageIdRoute
  '/api/telemetry/logs': typeof ApiTelemetryLogsRoute
  '/api/telemetry/sentry-tunnel': typeof ApiTelemetrySentryTunnelRoute
  '/pages': typeof ShellPagesIndexRoute
  '/api/telemetry/otel/v1/metrics': typeof ApiTelemetryOtelV1MetricsRoute
  '/api/telemetry/otel/v1/traces': typeof ApiTelemetryOtelV1TracesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/clusters': typeof ShellClustersRoute
  '/_shell/entities': typeof ShellEntitiesRoute
  '/_shell/jobs': typeof ShellJobsRoute
  '/_shell/models': typeof ShellModelsRoute
  '/_shell/search': typeof ShellSearchRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/system': typeof ShellSystemRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/pages/$pageId': typeof ShellPagesPageIdRoute
  '/api/telemetry/logs': typeof ApiTelemetryLogsRoute
  '/api/telemetry/sentry-tunnel': typeof ApiTelemetrySentryTunnelRoute
  '/_shell/pages/': typeof ShellPagesIndexRoute
  '/api/telemetry/otel/v1/metrics': typeof ApiTelemetryOtelV1MetricsRoute
  '/api/telemetry/otel/v1/traces': typeof ApiTelemetryOtelV1TracesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clusters'
    | '/entities'
    | '/jobs'
    | '/models'
    | '/search'
    | '/settings'
    | '/system'
    | '/pages/$pageId'
    | '/api/telemetry/logs'
    | '/api/telemetry/sentry-tunnel'
    | '/pages/'
    | '/api/telemetry/otel/v1/metrics'
    | '/api/telemetry/otel/v1/traces'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clusters'
    | '/entities'
    | '/jobs'
    | '/models'
    | '/search'
    | '/settings'
    | '/system'
    | '/'
    | '/pages/$pageId'
    | '/api/telemetry/logs'
    | '/api/telemetry/sentry-tunnel'
    | '/pages'
    | '/api/telemetry/otel/v1/metrics'
    | '/api/telemetry/otel/v1/traces'
  id:
    | '__root__'
    | '/_shell'
    | '/_shell/clusters'
    | '/_shell/entities'
    | '/_shell/jobs'
    | '/_shell/models'
    | '/_shell/search'
    | '/_shell/settings'
    | '/_shell/system'
    | '/_shell/'
    | '/_shell/pages/$pageId'
    | '/api/telemetry/logs'
    | '/api/telemetry/sentry-tunnel'
    | '/_shell/pages/'
    | '/api/telemetry/otel/v1/metrics'
    | '/api/telemetry/otel/v1/traces'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  ApiTelemetryLogsRoute: typeof ApiTelemetryLogsRoute
  ApiTelemetrySentryTunnelRoute: typeof ApiTelemetrySentryTunnelRoute
  ApiTelemetryOtelV1MetricsRoute: typeof ApiTelemetryOtelV1MetricsRoute
  ApiTelemetryOtelV1TracesRoute: typeof ApiTelemetryOtelV1TracesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/system': {
      id: '/_shell/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof ShellSystemRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/search': {
      id: '/_shell/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof ShellSearchRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/models': {
      id: '/_shell/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ShellModelsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/jobs': {
      id: '/_shell/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof ShellJobsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/entities': {
      id: '/_shell/entities'
      path: '/entities'
      fullPath: '/entities'
      preLoaderRoute: typeof ShellEntitiesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/clusters': {
      id: '/_shell/clusters'
      path: '/clusters'
      fullPath: '/clusters'
      preLoaderRoute: typeof ShellClustersRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pages/': {
      id: '/_shell/pages/'
      path: '/pages'
      fullPath: '/pages/'
      preLoaderRoute: typeof ShellPagesIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/api/telemetry/sentry-tunnel': {
      id: '/api/telemetry/sentry-tunnel'
      path: '/api/telemetry/sentry-tunnel'
      fullPath: '/api/telemetry/sentry-tunnel'
      preLoaderRoute: typeof ApiTelemetrySentryTunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telemetry/logs': {
      id: '/api/telemetry/logs'
      path: '/api/telemetry/logs'
      fullPath: '/api/telemetry/logs'
      preLoaderRoute: typeof ApiTelemetryLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/pages/$pageId': {
      id: '/_shell/pages/$pageId'
      path: '/pages/$pageId'
      fullPath: '/pages/$pageId'
      preLoaderRoute: typeof ShellPagesPageIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/api/telemetry/otel/v1/traces': {
      id: '/api/telemetry/otel/v1/traces'
      path: '/api/telemetry/otel/v1/traces'
      fullPath: '/api/telemetry/otel/v1/traces'
      preLoaderRoute: typeof ApiTelemetryOtelV1TracesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telemetry/otel/v1/metrics': {
      id: '/api/telemetry/otel/v1/metrics'
      path: '/api/telemetry/otel/v1/metrics'
      fullPath: '/api/telemetry/otel/v1/metrics'
      preLoaderRoute: typeof ApiTelemetryOtelV1MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShellRouteChildren {
  ShellClustersRoute: typeof ShellClustersRoute
  ShellEntitiesRoute: typeof ShellEntitiesRoute
  ShellJobsRoute: typeof ShellJobsRoute
  ShellModelsRoute: typeof ShellModelsRoute
  ShellSearchRoute: typeof ShellSearchRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellSystemRoute: typeof ShellSystemRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellPagesPageIdRoute: typeof ShellPagesPageIdRoute
  ShellPagesIndexRoute: typeof ShellPagesIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellClustersRoute: ShellClustersRoute,
  ShellEntitiesRoute: ShellEntitiesRoute,
  ShellJobsRoute: ShellJobsRoute,
  ShellModelsRoute: ShellModelsRoute,
  ShellSearchRoute: ShellSearchRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellSystemRoute: ShellSystemRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellPagesPageIdRoute: ShellPagesPageIdRoute,
  ShellPagesIndexRoute: ShellPagesIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  ApiTelemetryLogsRoute: ApiTelemetryLogsRoute,
  ApiTelemetrySentryTunnelRoute: ApiTelemetrySentryTunnelRoute,
  ApiTelemetryOtelV1MetricsRoute: ApiTelemetryOtelV1MetricsRoute,
  ApiTelemetryOtelV1TracesRoute: ApiTelemetryOtelV1TracesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
